packages:
  - packages/*
  - docs
  - test
  - test/*
  - scripts/*
  - examples/*

onlyBuiltDependencies:
  - '@mui/internal-babel-plugin-display-name'
  - '@mui/monorepo'
  - '@vvago/vale'
  - core-js
  - esbuild
  - nx
  - sharp
  - unrs-resolver

overrides:
  '@babel/core': ^7.28.0
  '@babel/plugin-transform-runtime': ^7.28.0
  '@babel/preset-env': ^7.28.0
  '@babel/preset-react': ^7.27.1
  '@babel/preset-typescript': ^7.27.1
  '@babel/types': ^7.28.2
  '@types/node': ^18.19.121
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  internal-docs-infra: link:../../.local/share/pnpm/global/5/node_modules/@mui/internal-docs-infra
